/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import DAO.NoteFraisDAO;
import Metier.User;
import java.awt.Color;
import static java.lang.String.valueOf;

/**
 *
 * @author ibrah
 */
public class Commercial extends javax.swing.JFrame {
    private User currentUser;

    /**
     * Creates new form Commercial
     */
    
    public Commercial(){
        initComponents();
        this.setTitle("Commercial");
        this.setVisible(true);
    }
    
    public Commercial(User user) {
        this.currentUser = user;
        initComponents();
        this.setVisible(true);
        this.setTitle("Commercial");
        NotesActivity.setVisible(false);
        AccountActivity.setVisible(false);
        getAccountInfo();
    }
    
    
    public void getAccountInfo(){
        String id = valueOf(this.currentUser.getId());
        this.IDField.setText(id);
        this.nomField.setText(this.currentUser.getLastName());
        this.prenomField.setText(this.currentUser.getFirstName());
        this.telField.setText(this.currentUser.getTelephone());
        this.emailField.setText(this.currentUser.getEmail());
        this.villeField.setText(this.currentUser.getVille());
        this.cpField.setText(this.currentUser.getCode_postal());
        this.typeField.setText(this.currentUser.getAccountType());
    }
    
    
    
    
    public void prepareWelcome(String name){
        this.welcomeTXT.setText("Bienvenue "+name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContent = new javax.swing.JPanel();
        StatsActivity = new javax.swing.JPanel();
        NotesActivity = new javax.swing.JPanel();
        addNoteFraisBTN = new javax.swing.JPanel();
        addNotefraisLABEL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        AccountActivity = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IDField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomField = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prenomField = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        villeField = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cpField = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        telField = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        typeField = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        welcomeTXT = new javax.swing.JLabel();
        myaccBTN = new javax.swing.JPanel();
        myAccountBTN = new javax.swing.JLabel();
        notesBTN = new javax.swing.JPanel();
        notesFraisBTN = new javax.swing.JLabel();
        statsBTN = new javax.swing.JPanel();
        statsLabel = new javax.swing.JLabel();
        signoutBTN = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainContent.setBackground(new java.awt.Color(35, 38, 53));

        StatsActivity.setBackground(new java.awt.Color(35, 38, 53));
        StatsActivity.setForeground(new java.awt.Color(190, 190, 190));

        javax.swing.GroupLayout StatsActivityLayout = new javax.swing.GroupLayout(StatsActivity);
        StatsActivity.setLayout(StatsActivityLayout);
        StatsActivityLayout.setHorizontalGroup(
            StatsActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        StatsActivityLayout.setVerticalGroup(
            StatsActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        NotesActivity.setBackground(new java.awt.Color(35, 38, 53));
        NotesActivity.setForeground(new java.awt.Color(190, 190, 190));
        NotesActivity.setMaximumSize(new java.awt.Dimension(700, 550));
        NotesActivity.setMinimumSize(new java.awt.Dimension(700, 550));
        NotesActivity.setPreferredSize(new java.awt.Dimension(582, 400));

        addNoteFraisBTN.setBackground(new java.awt.Color(35, 38, 53));
        addNoteFraisBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(92, 235, 181), 1, true));

        addNotefraisLABEL.setBackground(new java.awt.Color(35, 38, 53));
        addNotefraisLABEL.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        addNotefraisLABEL.setForeground(new java.awt.Color(255, 255, 255));
        addNotefraisLABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addNotefraisLABEL.setText("Ajouter");
        addNotefraisLABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addNotefraisLABELMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addNotefraisLABELMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout addNoteFraisBTNLayout = new javax.swing.GroupLayout(addNoteFraisBTN);
        addNoteFraisBTN.setLayout(addNoteFraisBTNLayout);
        addNoteFraisBTNLayout.setHorizontalGroup(
            addNoteFraisBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNoteFraisBTNLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addNotefraisLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addNoteFraisBTNLayout.setVerticalGroup(
            addNoteFraisBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNoteFraisBTNLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addNotefraisLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 190, 190));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mes notes de frais");

        jSeparator2.setBackground(new java.awt.Color(190, 190, 190));
        jSeparator2.setForeground(new java.awt.Color(190, 190, 190));

        javax.swing.GroupLayout NotesActivityLayout = new javax.swing.GroupLayout(NotesActivity);
        NotesActivity.setLayout(NotesActivityLayout);
        NotesActivityLayout.setHorizontalGroup(
            NotesActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NotesActivityLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(NotesActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addNoteFraisBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(205, 205, 205))
        );
        NotesActivityLayout.setVerticalGroup(
            NotesActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NotesActivityLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358)
                .addComponent(addNoteFraisBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        AccountActivity.setBackground(new java.awt.Color(35, 38, 53));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(190, 190, 190));
        jLabel3.setText("ID :");

        IDField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        IDField.setForeground(new java.awt.Color(190, 190, 190));
        IDField.setText("ID");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 190, 190));
        jLabel4.setText("Nom  :");

        nomField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        nomField.setForeground(new java.awt.Color(190, 190, 190));
        nomField.setText("NOM");

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(190, 190, 190));
        jLabel7.setText("Prenom :");

        prenomField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        prenomField.setForeground(new java.awt.Color(190, 190, 190));
        prenomField.setText("PRENOM");

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(190, 190, 190));
        jLabel9.setText("Email :");

        emailField.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(190, 190, 190));
        emailField.setText("EMAIL");

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(190, 190, 190));
        jLabel11.setText("Ville :");

        villeField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        villeField.setForeground(new java.awt.Color(190, 190, 190));
        villeField.setText("VILLE");

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(190, 190, 190));
        jLabel13.setText("Code postal");

        cpField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        cpField.setForeground(new java.awt.Color(190, 190, 190));
        cpField.setText("CODEPOSTAL");

        jLabel15.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(190, 190, 190));
        jLabel15.setText("Telephone");

        telField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        telField.setForeground(new java.awt.Color(190, 190, 190));
        telField.setText("TELEPHONE");

        jLabel17.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(190, 190, 190));
        jLabel17.setText("Type Compte :");

        typeField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        typeField.setForeground(new java.awt.Color(190, 190, 190));
        typeField.setText("TYPE");

        javax.swing.GroupLayout AccountActivityLayout = new javax.swing.GroupLayout(AccountActivity);
        AccountActivity.setLayout(AccountActivityLayout);
        AccountActivityLayout.setHorizontalGroup(
            AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountActivityLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telField, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(prenomField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(villeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cpField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(typeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(IDField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(193, 193, 193))
        );
        AccountActivityLayout.setVerticalGroup(
            AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountActivityLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IDField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(prenomField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(telField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emailField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(villeField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cpField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(typeField))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NotesActivity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(StatsActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NotesActivity, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(StatsActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(mainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 630, 530));

        sidepanel.setBackground(new java.awt.Color(57, 55, 76));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 190, 190));
        jLabel1.setText("Easy Expense");

        jSeparator1.setBackground(new java.awt.Color(222, 222, 222));
        jSeparator1.setForeground(new java.awt.Color(222, 222, 222));

        welcomeTXT.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        welcomeTXT.setForeground(new java.awt.Color(190, 190, 190));
        welcomeTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeTXT.setText("Bienvenue");

        myaccBTN.setBackground(new java.awt.Color(57, 55, 76));
        myaccBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myaccBTNMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                myaccBTNMouseReleased(evt);
            }
        });

        myAccountBTN.setBackground(new java.awt.Color(0, 0, 0));
        myAccountBTN.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        myAccountBTN.setForeground(new java.awt.Color(190, 190, 190));
        myAccountBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myAccountBTN.setText("Mon compte");
        myAccountBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myAccountBTNMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myAccountBTNMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                myAccountBTNMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout myaccBTNLayout = new javax.swing.GroupLayout(myaccBTN);
        myaccBTN.setLayout(myaccBTNLayout);
        myaccBTNLayout.setHorizontalGroup(
            myaccBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myaccBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myAccountBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        myaccBTNLayout.setVerticalGroup(
            myaccBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myaccBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myAccountBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        notesBTN.setBackground(new java.awt.Color(57, 55, 76));

        notesFraisBTN.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        notesFraisBTN.setForeground(new java.awt.Color(190, 190, 190));
        notesFraisBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notesFraisBTN.setText("Mes notes de frais");
        notesFraisBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notesFraisBTNMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                notesFraisBTNMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout notesBTNLayout = new javax.swing.GroupLayout(notesBTN);
        notesBTN.setLayout(notesBTNLayout);
        notesBTNLayout.setHorizontalGroup(
            notesBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notesBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notesFraisBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        notesBTNLayout.setVerticalGroup(
            notesBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notesBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notesFraisBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        statsBTN.setBackground(new java.awt.Color(57, 55, 76));

        statsLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        statsLabel.setForeground(new java.awt.Color(190, 190, 190));
        statsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statsLabel.setText("Statistiques");
        statsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statsLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                statsLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout statsBTNLayout = new javax.swing.GroupLayout(statsBTN);
        statsBTN.setLayout(statsBTNLayout);
        statsBTNLayout.setHorizontalGroup(
            statsBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        statsBTNLayout.setVerticalGroup(
            statsBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        signoutBTN.setBackground(new java.awt.Color(57, 55, 76));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(190, 190, 190));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deconnexion");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout signoutBTNLayout = new javax.swing.GroupLayout(signoutBTN);
        signoutBTN.setLayout(signoutBTNLayout);
        signoutBTNLayout.setHorizontalGroup(
            signoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signoutBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        signoutBTNLayout.setVerticalGroup(
            signoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signoutBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(myaccBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notesBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(welcomeTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statsBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(signoutBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcomeTXT)
                .addGap(57, 57, 57)
                .addComponent(myaccBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myAccountBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccountBTNMousePressed
        myaccBTN.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_myAccountBTNMousePressed

    private void myAccountBTNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccountBTNMouseReleased
        myaccBTN.setBackground(new Color(57,55,76));
    }//GEN-LAST:event_myAccountBTNMouseReleased

    private void myaccBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccBTNMousePressed
        myaccBTN.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_myaccBTNMousePressed

    private void myaccBTNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccBTNMouseReleased
        myaccBTN.setBackground(new Color(57,55,76));
    }//GEN-LAST:event_myaccBTNMouseReleased

    private void notesFraisBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesFraisBTNMousePressed
        notesBTN.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_notesFraisBTNMousePressed

    private void notesFraisBTNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesFraisBTNMouseReleased
        notesBTN.setBackground(new Color(57,55,76));
        this.AccountActivity.setVisible(false);
        this.StatsActivity.setVisible(false);
        this.NotesActivity.setVisible(true);
    }//GEN-LAST:event_notesFraisBTNMouseReleased

    private void myAccountBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccountBTNMouseClicked
        this.NotesActivity.setVisible(false);
        this.StatsActivity.setVisible(false);
        this.AccountActivity.setVisible(true);
    }//GEN-LAST:event_myAccountBTNMouseClicked

    private void statsLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMousePressed
        statsBTN.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_statsLabelMousePressed

    private void statsLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsLabelMouseReleased
        statsBTN.setBackground(new Color(57,55,76));
        this.AccountActivity.setVisible(false);
        this.NotesActivity.setVisible(false);
        this.StatsActivity.setVisible(true);
    }//GEN-LAST:event_statsLabelMouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        signoutBTN.setBackground(new Color(57,55,76));
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        signoutBTN.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        LoginActivity f = new LoginActivity();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addNotefraisLABELMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNotefraisLABELMousePressed
        this.addNoteFraisBTN.setBackground(new Color(92,235,181));
    }//GEN-LAST:event_addNotefraisLABELMousePressed

    private void addNotefraisLABELMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNotefraisLABELMouseReleased
        this.addNoteFraisBTN.setBackground(new Color(35,38,53));
        
        addNote f = new addNote();
        //this.setVisible(false);
    }//GEN-LAST:event_addNotefraisLABELMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        Commercial f = new Commercial();
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountActivity;
    private javax.swing.JLabel IDField;
    private javax.swing.JPanel NotesActivity;
    private javax.swing.JPanel StatsActivity;
    private javax.swing.JPanel addNoteFraisBTN;
    private javax.swing.JLabel addNotefraisLABEL;
    private javax.swing.JLabel cpField;
    private javax.swing.JLabel emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainContent;
    private javax.swing.JLabel myAccountBTN;
    private javax.swing.JPanel myaccBTN;
    private javax.swing.JLabel nomField;
    private javax.swing.JPanel notesBTN;
    private javax.swing.JLabel notesFraisBTN;
    private javax.swing.JLabel prenomField;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel signoutBTN;
    private javax.swing.JPanel statsBTN;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JLabel telField;
    private javax.swing.JLabel typeField;
    private javax.swing.JLabel villeField;
    private javax.swing.JLabel welcomeTXT;
    // End of variables declaration//GEN-END:variables
}
