/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import Metier.NoteFrais;
import Metier.User;
import java.awt.Color;

/**
 *
 * @author ibragim.abubakarov
 */
public class Comptable extends javax.swing.JFrame {
    private User currentComptable;

    /**
     * Creates new form Comptable
     */
    public Comptable(User currentCom) {
        initComponents();
        this.currentComptable = currentCom;
        this.setSize(870, 550);
        this.setTitle("Comptable - " + currentCom.getFirstName());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        this.prepareWelcome();
        initAccountActivity();
    }
    
    public Comptable(){
        initComponents();
    }
    
    
    public void initAccountActivity(){
        this.AccountActivity.setVisible(true);
        this.GestionCommercialActivity.setVisible(false);
        this.ListeNoteFraisActivity.setVisible(false);
        this.listeCommercialActivity.setVisible(false);
        
        
    }
    
    
    
    public void initCurrentUser(){
        String currentUID = String.valueOf(this.currentComptable.getId());
        IDField.setText(currentUID);
        
    }
    
    
    public void initCurrentComptable(){
        String currentID = String.valueOf(this.currentComptable.getId());
        IDField.setText(currentID);
        nomField.setText(this.currentComptable.getLastName());
        prenomField.setText(this.currentComptable.getFirstName());
        telField.setText(this.currentComptable.getTelephone());
        emailField.setText(this.currentComptable.getEmail());
        villeField.setText(this.currentComptable.getVille());
        cpField.setText(this.currentComptable.getCode_postal());
        typeField.setText(this.currentComptable.getAccountType());
    }
    
    
    public void prepareWelcome(){
        this.welcomeTXT.setText("Bienvenue "+ currentComptable.getFirstName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        welcomeTXT = new javax.swing.JLabel();
        myaccBTN = new javax.swing.JPanel();
        myAccountBTN = new javax.swing.JLabel();
        GestionCommercialBTN = new javax.swing.JPanel();
        GestionCommercialLabel = new javax.swing.JLabel();
        listeNoteFraisBTN = new javax.swing.JPanel();
        listeNoteFraisLabel = new javax.swing.JLabel();
        signoutBTN = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        listeCommercial = new javax.swing.JPanel();
        listeCommercialLabel = new javax.swing.JLabel();
        mainContent = new javax.swing.JPanel();
        GestionCommercialActivity = new javax.swing.JPanel();
        listeCommercialActivity = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        currentCommercial = new javax.swing.JComboBox<>();
        printBTN = new javax.swing.JPanel();
        printLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        ListeNoteFraisActivity = new javax.swing.JPanel();
        AccountActivity = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IDField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomField = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prenomField = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        villeField = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cpField = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        telField = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        typeField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidepanel.setBackground(new java.awt.Color(57, 55, 76));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 190, 190));
        jLabel1.setText("Easy Expense");

        jSeparator1.setBackground(new java.awt.Color(222, 222, 222));
        jSeparator1.setForeground(new java.awt.Color(222, 222, 222));

        welcomeTXT.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        welcomeTXT.setForeground(new java.awt.Color(190, 190, 190));
        welcomeTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeTXT.setText("Bienvenue");

        myaccBTN.setBackground(new java.awt.Color(57, 55, 76));
        myaccBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myaccBTNMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                myaccBTNMouseReleased(evt);
            }
        });

        myAccountBTN.setBackground(new java.awt.Color(0, 0, 0));
        myAccountBTN.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        myAccountBTN.setForeground(new java.awt.Color(190, 190, 190));
        myAccountBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myAccountBTN.setText("Mon compte");
        myAccountBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myAccountBTNMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myAccountBTNMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                myAccountBTNMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout myaccBTNLayout = new javax.swing.GroupLayout(myaccBTN);
        myaccBTN.setLayout(myaccBTNLayout);
        myaccBTNLayout.setHorizontalGroup(
            myaccBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myAccountBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        myaccBTNLayout.setVerticalGroup(
            myaccBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myAccountBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        GestionCommercialBTN.setBackground(new java.awt.Color(57, 55, 76));

        GestionCommercialLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        GestionCommercialLabel.setForeground(new java.awt.Color(190, 190, 190));
        GestionCommercialLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GestionCommercialLabel.setText("Gestion des commerciaux");
        GestionCommercialLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GestionCommercialLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GestionCommercialLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout GestionCommercialBTNLayout = new javax.swing.GroupLayout(GestionCommercialBTN);
        GestionCommercialBTN.setLayout(GestionCommercialBTNLayout);
        GestionCommercialBTNLayout.setHorizontalGroup(
            GestionCommercialBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GestionCommercialLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GestionCommercialBTNLayout.setVerticalGroup(
            GestionCommercialBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionCommercialBTNLayout.createSequentialGroup()
                .addComponent(GestionCommercialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        listeNoteFraisBTN.setBackground(new java.awt.Color(57, 55, 76));

        listeNoteFraisLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        listeNoteFraisLabel.setForeground(new java.awt.Color(190, 190, 190));
        listeNoteFraisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listeNoteFraisLabel.setText("Liste des notes de frais");
        listeNoteFraisLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listeNoteFraisLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listeNoteFraisLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout listeNoteFraisBTNLayout = new javax.swing.GroupLayout(listeNoteFraisBTN);
        listeNoteFraisBTN.setLayout(listeNoteFraisBTNLayout);
        listeNoteFraisBTNLayout.setHorizontalGroup(
            listeNoteFraisBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listeNoteFraisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listeNoteFraisBTNLayout.setVerticalGroup(
            listeNoteFraisBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeNoteFraisBTNLayout.createSequentialGroup()
                .addComponent(listeNoteFraisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        signoutBTN.setBackground(new java.awt.Color(57, 55, 76));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(190, 190, 190));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deconnexion");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout signoutBTNLayout = new javax.swing.GroupLayout(signoutBTN);
        signoutBTN.setLayout(signoutBTNLayout);
        signoutBTNLayout.setHorizontalGroup(
            signoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        signoutBTNLayout.setVerticalGroup(
            signoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signoutBTNLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        listeCommercial.setBackground(new java.awt.Color(57, 55, 76));

        listeCommercialLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        listeCommercialLabel.setForeground(new java.awt.Color(190, 190, 190));
        listeCommercialLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listeCommercialLabel.setText("Liste des commerciaux");
        listeCommercialLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listeCommercialLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listeCommercialLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout listeCommercialLayout = new javax.swing.GroupLayout(listeCommercial);
        listeCommercial.setLayout(listeCommercialLayout);
        listeCommercialLayout.setHorizontalGroup(
            listeCommercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listeCommercialLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listeCommercialLayout.setVerticalGroup(
            listeCommercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listeCommercialLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myaccBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GestionCommercialBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(welcomeTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listeNoteFraisBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(signoutBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(listeCommercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcomeTXT)
                .addGap(27, 27, 27)
                .addComponent(myaccBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GestionCommercialBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listeCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listeNoteFraisBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        mainContent.setBackground(new java.awt.Color(35, 38, 53));

        GestionCommercialActivity.setBackground(new java.awt.Color(35, 38, 53));
        GestionCommercialActivity.setForeground(new java.awt.Color(190, 190, 190));

        javax.swing.GroupLayout GestionCommercialActivityLayout = new javax.swing.GroupLayout(GestionCommercialActivity);
        GestionCommercialActivity.setLayout(GestionCommercialActivityLayout);
        GestionCommercialActivityLayout.setHorizontalGroup(
            GestionCommercialActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        GestionCommercialActivityLayout.setVerticalGroup(
            GestionCommercialActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        listeCommercialActivity.setBackground(new java.awt.Color(35, 38, 53));
        listeCommercialActivity.setForeground(new java.awt.Color(190, 190, 190));
        listeCommercialActivity.setMaximumSize(new java.awt.Dimension(700, 550));
        listeCommercialActivity.setMinimumSize(new java.awt.Dimension(700, 550));
        listeCommercialActivity.setPreferredSize(new java.awt.Dimension(582, 400));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Liste des commerciaux");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        currentCommercial.setBackground(new java.awt.Color(35, 38, 53));
        currentCommercial.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        currentCommercial.setForeground(new java.awt.Color(255, 255, 255));

        printBTN.setBackground(new java.awt.Color(35, 38, 53));
        printBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(92, 235, 181), 1, true));

        printLabel.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        printLabel.setForeground(new java.awt.Color(255, 255, 255));
        printLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printLabel.setText("Imprimer");
        printLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                printLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                printLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout printBTNLayout = new javax.swing.GroupLayout(printBTN);
        printBTN.setLayout(printBTNLayout);
        printBTNLayout.setHorizontalGroup(
            printBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printBTNLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(printLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        printBTNLayout.setVerticalGroup(
            printBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(printLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jScrollPane2.setBackground(new java.awt.Color(35, 38, 53));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout listeCommercialActivityLayout = new javax.swing.GroupLayout(listeCommercialActivity);
        listeCommercialActivity.setLayout(listeCommercialActivityLayout);
        listeCommercialActivityLayout.setHorizontalGroup(
            listeCommercialActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeCommercialActivityLayout.createSequentialGroup()
                .addGroup(listeCommercialActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeCommercialActivityLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(listeCommercialActivityLayout.createSequentialGroup()
                        .addGroup(listeCommercialActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(listeCommercialActivityLayout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(listeCommercialActivityLayout.createSequentialGroup()
                                .addGroup(listeCommercialActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(listeCommercialActivityLayout.createSequentialGroup()
                                        .addGap(340, 340, 340)
                                        .addComponent(currentCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeCommercialActivityLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)))
                                .addComponent(printBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        listeCommercialActivityLayout.setVerticalGroup(
            listeCommercialActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeCommercialActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(listeCommercialActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listeCommercialActivityLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(currentCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(listeCommercialActivityLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(printBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(215, 215, 215))
        );

        ListeNoteFraisActivity.setBackground(new java.awt.Color(35, 38, 53));
        ListeNoteFraisActivity.setForeground(new java.awt.Color(190, 190, 190));

        javax.swing.GroupLayout ListeNoteFraisActivityLayout = new javax.swing.GroupLayout(ListeNoteFraisActivity);
        ListeNoteFraisActivity.setLayout(ListeNoteFraisActivityLayout);
        ListeNoteFraisActivityLayout.setHorizontalGroup(
            ListeNoteFraisActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        ListeNoteFraisActivityLayout.setVerticalGroup(
            ListeNoteFraisActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        AccountActivity.setBackground(new java.awt.Color(35, 38, 53));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(190, 190, 190));
        jLabel3.setText("ID :");

        IDField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        IDField.setForeground(new java.awt.Color(190, 190, 190));
        IDField.setText("ID");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 190, 190));
        jLabel4.setText("Nom  :");

        nomField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        nomField.setForeground(new java.awt.Color(190, 190, 190));
        nomField.setText("NOM");

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(190, 190, 190));
        jLabel7.setText("Prenom :");

        prenomField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        prenomField.setForeground(new java.awt.Color(190, 190, 190));
        prenomField.setText("PRENOM");

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(190, 190, 190));
        jLabel9.setText("Email :");

        emailField.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(190, 190, 190));
        emailField.setText("EMAIL");

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(190, 190, 190));
        jLabel11.setText("Ville :");

        villeField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        villeField.setForeground(new java.awt.Color(190, 190, 190));
        villeField.setText("VILLE");

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(190, 190, 190));
        jLabel13.setText("Code postal");

        cpField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        cpField.setForeground(new java.awt.Color(190, 190, 190));
        cpField.setText("CODEPOSTAL");

        jLabel15.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(190, 190, 190));
        jLabel15.setText("Telephone");

        telField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        telField.setForeground(new java.awt.Color(190, 190, 190));
        telField.setText("TELEPHONE");

        jLabel17.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(190, 190, 190));
        jLabel17.setText("Type Compte :");

        typeField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        typeField.setForeground(new java.awt.Color(190, 190, 190));
        typeField.setText("TYPE");

        javax.swing.GroupLayout AccountActivityLayout = new javax.swing.GroupLayout(AccountActivity);
        AccountActivity.setLayout(AccountActivityLayout);
        AccountActivityLayout.setHorizontalGroup(
            AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountActivityLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telField, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(prenomField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(villeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cpField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(typeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(IDField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(193, 193, 193))
        );
        AccountActivityLayout.setVerticalGroup(
            AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountActivityLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IDField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(prenomField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(telField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emailField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(villeField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cpField))
                .addGap(18, 18, 18)
                .addGroup(AccountActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(typeField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(listeCommercialActivity, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainContentLayout.createSequentialGroup()
                    .addComponent(ListeNoteFraisActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(GestionCommercialActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentLayout.createSequentialGroup()
                .addComponent(AccountActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainContentLayout.createSequentialGroup()
                    .addComponent(listeCommercialActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 541, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ListeNoteFraisActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainContentLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(GestionCommercialActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myAccountBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccountBTNMouseClicked
        
    }//GEN-LAST:event_myAccountBTNMouseClicked

    private void myAccountBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccountBTNMousePressed
        myaccBTN.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_myAccountBTNMousePressed

    private void myAccountBTNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccountBTNMouseReleased
        myaccBTN.setBackground(new Color(57,55,76));
        this.AccountActivity.setVisible(true);
        this.listeCommercialActivity.setVisible(false);
        this.ListeNoteFraisActivity.setVisible(false);
        this.GestionCommercialActivity.setVisible(false);
    }//GEN-LAST:event_myAccountBTNMouseReleased

    private void myaccBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccBTNMousePressed
        myaccBTN.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_myaccBTNMousePressed

    private void myaccBTNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccBTNMouseReleased
        myaccBTN.setBackground(new Color(57,55,76));
    }//GEN-LAST:event_myaccBTNMouseReleased

    private void GestionCommercialLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionCommercialLabelMousePressed
        GestionCommercialBTN.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_GestionCommercialLabelMousePressed

    private void GestionCommercialLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionCommercialLabelMouseReleased
        GestionCommercialBTN.setBackground(new Color(57,55,76));
        this.GestionCommercialActivity.setVisible(true);
        this.AccountActivity.setVisible(false);
        this.ListeNoteFraisActivity.setVisible(false);
        this.listeCommercialActivity.setVisible(false);
    }//GEN-LAST:event_GestionCommercialLabelMouseReleased

    private void listeCommercialLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeCommercialLabelMousePressed
        listeCommercial.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_listeCommercialLabelMousePressed

    private void listeCommercialLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeCommercialLabelMouseReleased
        listeCommercial.setBackground(new Color(57,55,76));
        this.GestionCommercialActivity.setVisible(false);
        this.AccountActivity.setVisible(false);
        this.ListeNoteFraisActivity.setVisible(false);
        this.listeCommercialActivity.setVisible(true);
    }//GEN-LAST:event_listeCommercialLabelMouseReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        signoutBTN.setBackground(new Color(43, 42, 58));
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        signoutBTN.setBackground(new Color(57,55,76));
        
        LoginActivity f = new LoginActivity();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseReleased

    private void listeNoteFraisLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeNoteFraisLabelMousePressed
        listeNoteFraisBTN.setBackground(new Color(43,42,58));
    }//GEN-LAST:event_listeNoteFraisLabelMousePressed

    private void listeNoteFraisLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeNoteFraisLabelMouseReleased
        listeNoteFraisBTN.setBackground(new Color(57,55,76));
        this.GestionCommercialActivity.setVisible(false);
        this.AccountActivity.setVisible(false);
        this.ListeNoteFraisActivity.setVisible(true);
        this.listeCommercialActivity.setVisible(false);
    }//GEN-LAST:event_listeNoteFraisLabelMouseReleased

    private void printLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printLabelMousePressed
        printBTN.setBackground(new Color(92,235,181));
    }//GEN-LAST:event_printLabelMousePressed

    private void printLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printLabelMouseReleased
        printBTN.setBackground(new Color(35,38,53));
    }//GEN-LAST:event_printLabelMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountActivity;
    private javax.swing.JPanel GestionCommercialActivity;
    private javax.swing.JPanel GestionCommercialBTN;
    private javax.swing.JLabel GestionCommercialLabel;
    private javax.swing.JLabel IDField;
    private javax.swing.JPanel ListeNoteFraisActivity;
    private javax.swing.JLabel cpField;
    private javax.swing.JComboBox<String> currentCommercial;
    private javax.swing.JLabel emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel listeCommercial;
    private javax.swing.JPanel listeCommercialActivity;
    private javax.swing.JLabel listeCommercialLabel;
    private javax.swing.JPanel listeNoteFraisBTN;
    private javax.swing.JLabel listeNoteFraisLabel;
    private javax.swing.JPanel mainContent;
    private javax.swing.JLabel myAccountBTN;
    private javax.swing.JPanel myaccBTN;
    private javax.swing.JLabel nomField;
    private javax.swing.JLabel prenomField;
    private javax.swing.JPanel printBTN;
    private javax.swing.JLabel printLabel;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel signoutBTN;
    private javax.swing.JLabel telField;
    private javax.swing.JLabel typeField;
    private javax.swing.JLabel villeField;
    private javax.swing.JLabel welcomeTXT;
    // End of variables declaration//GEN-END:variables
}
